name: Github-Actions-ubuntu

on:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'Enable SSH connection to Actions'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Create up directory
      run: mkdir up
      
    - name: Use tmate connect ssh
      uses: mxschmitt/action-tmate@v3.17
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
            

    - name: Upload up directory File
      uses: actions/upload-artifact@v3
      with:
          name: Upload file
          path: ./up
